// Placeholder data so the UI is fully browsable before the backend/API exists.
// Every field here mirrors the real Product schema (see docs/DATABASE.md) so
// swapping this for `productService.list()` requires no component changes.

export const demoProducts = [
  {
    id: "p1",
    title: "Apple iPhone 13 128GB — Good Condition",
    price: 32999,
    condition: "Good",
    location: "Jaipur, RJ",
    image: "https://images.unsplash.com/photo-1632661674596-df8be070a5c5?w=600&q=80",
    sellerName: "Aarav M.",
    sellerVerified: true,
    category: "Mobiles",
  },
  {
    id: "p2",
    title: "Sony WH-1000XM4 Wireless Headphones",
    price: 14500,
    condition: "Like New",
    location: "Mumbai, MH",
    image: "https://images.unsplash.com/photo-1546435770-a3e426bf472b?w=600&q=80",
    sellerName: "Priya S.",
    sellerVerified: true,
    category: "Electronics",
  },
  {
    id: "p3",
    title: "Herman Miller Aeron Chair, Size B",
    price: 28000,
    condition: "Good",
    location: "Bengaluru, KA",
    image: "https://images.unsplash.com/photo-1592078615290-033ee584e267?w=600&q=80",
    sellerName: "Rohit K.",
    sellerVerified: false,
    category: "Furniture",
  },
  {
    id: "p4",
    title: "Canon EOS M50 Mirrorless Camera + Kit Lens",
    price: 38500,
    condition: "Good",
    location: "Delhi, DL",
    image: "https://images.unsplash.com/photo-1516035069371-29a1b244cc32?w=600&q=80",
    sellerName: "Neha T.",
    sellerVerified: true,
    category: "Electronics",
  },
  {
    id: "p5",
    title: "Trek Marlin 7 Mountain Bike, L Frame",
    price: 26000,
    condition: "Fair",
    location: "Pune, MH",
    image: "https://images.unsplash.com/photo-1485965120184-e220f721d03e?w=600&q=80",
    sellerName: "Karan V.",
    sellerVerified: false,
    category: "Sports",
  },
  {
    id: "p6",
    title: "ASUS ROG Strix G15 Gaming Laptop, RTX 3060",
    price: 68000,
    condition: "Good",
    location: "Hyderabad, TG",
    image: "https://images.unsplash.com/photo-1603302576837-37561b2e2302?w=600&q=80",
    sellerName: "Ishaan D.",
    sellerVerified: true,
    category: "Laptops",
  },
  {
    id: "p7",
    title: "Nike Air Max 270, UK 9, Black/White",
    price: 4200,
    condition: "Like New",
    location: "Chennai, TN",
    image: "https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=600&q=80",
    sellerName: "Meera R.",
    sellerVerified: false,
    category: "Fashion",
  },
  {
    id: "p8",
    title: "IKEA Malm 6-Drawer Dresser, White",
    price: 7800,
    condition: "Good",
    location: "Ahmedabad, GJ",
    image: "https://images.unsplash.com/photo-1595428774223-ef52624120d2?w=600&q=80",
    sellerName: "Devansh P.",
    sellerVerified: true,
    category: "Furniture",
  },
];

export const demoCategories = [
  "Electronics", "Mobiles", "Laptops", "Gaming", "Fashion", "Furniture",
  "Home & Kitchen", "Books", "Sports", "Beauty", "Vehicles", "Collectibles",
];
